version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter

    branches:
      only: master

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      #- run:
      #    name: Run the application tests
      #    command: flutter test

      - run:
          name: Build the Android version
          command: flutter build apk 

      - run:
          name: Build the web version
          command:  flutter build web

      - store_artifacts:
          path: build/app/outputs/apk/app.apk
          destination: android/app.apk

      - store_artifacts:
          path: build/web
          destination: web
