version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter

    branches:
      only: master

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor
    
      - run:
          name: Run Flutter analyze
          command: flutter analyze

      #- run:
      #    name: Run the application tests
      #    command: flutter test

      - run:
          name: Build the Android version
          command: flutter build apk 

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
          destination: app-release.apk

      #- run:
      #    name: Build the web version
      #    command: |
      #      flutter channel beta
      #      flutter upgrade
      #      flutter config --enable-web
      #      flutter build web
      #      cd build
      #      zip -r web.zip web

      #- store_artifacts:
      #    path: build/web.zip
      #    destination: web.zip
